name: Update UptimeRobot IPs

on:
  schedule:
    - cron: '0 2 * * *'  # ogni giorno alle 04:00 CET (02:00 UTC)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download UptimeRobot IP list
        run: |
          curl -fSL https://uptimerobot.com/inc/files/ips/IPv4.txt \
          -H "User-Agent: Mozilla/5.0" \
          -o uptimerobot.txt
          echo "# updated at $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> uptimerobot.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git fetch origin main
          git checkout main
          git reset --hard origin/main

          git add uptimerobot.txt || true
          git commit -m "Update IPs" || echo "No changes to commit"
          git push origin main
